HELLO = "Hello! The current config is: \n"
ASK_FOR_CONFIG = "Do you want edit this file? [Y/n]: "
RESULT_FILE = "\n This is your config file. Is this correct? [Y/n] "
IDS_KEY = "instanceIds"
START_TIME_KEY = "startTime"
END_TIME_KEY = "endTime"
PERIOD_KEY = "period"
METRIC_KEY = "metricName"
